apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app
  namespace: jenkins-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-nodejs-app
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
        - name: simple-nodejs-app
          image: mohameddev006/simple-nodejs-app:latest
          resources:
          ports:
            - name: httpport
              containerPort: 3000
