apiVersion: v1
kind: Service
metadata:
  name: app-load-balancer
  namespace: jenkins-ns
spec:
  type: LoadBalancer
  selector:
    app: simple-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000