apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: application-ns
spec:
  type: LoadBalancer
  selector:
    app: simple-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000