name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
            docker build . --file jenkins.Dockerfile --tag mohameddev006/kubejenkins:latest
            docker login -u ${{ secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_PASS}}
            docker push mohameddev006/kubejenkins:1.0
